name: checks

on:
  push:
    branches: [ master ]

  pull_request:

jobs:
  coverage:

    runs-on: ubuntu-latest

    name: Coveralls code coverage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Installing dev dependencies
        run: npm ci

      - name: Test and collect coverage
        run: npm run coverage

      - name: Send coverage to coveralls.io
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  lint-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    name: Node ${{ matrix.node-version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Installing dev dependencies
        run: npm ci

      - name: Linting
        run: npm run lint

      - name: Test and collect coverage
        run: npm run coverage
